BadChCand:
  min_pfmet: 500.0
  min_pfcandid_pt: 500.0
  abs_pfcand_pdgid: 211
  min_dphi: 3.0 # Minimum dphi between pf-met and pf-candidate

GlbSTightHalo:
  min_pfmet: 200.0
  num_jets_ptgt25: 1
  num_jets_ptgt200: 1
  max_abs_pfmet_phi: 0.2
  min_abs_pfmet_phi: 2.9 
  min_jet_pt: 200.0
  max_abs_jet_eta: 2.4
  max_jet_chef: 0.01

BadPFMuon:
  min_pfmet: 200.0
  num_jets_ptgt25: 1
  num_jets_ptgt200: 1
  min_num_muon: 1
  min_muon_pt: 200.0
  min_dphi: 3.0 # Minimum dphi between pf-met and muon
  max_additional_muon_pt: 10.0
  min_delta_r: 0.4

EcalBadCal_U:
  min_pfmet: 200.0
  num_jets_ptgt25: 1
  num_jets_ptgt200: 1
  min_jet_pt: 200.0
  max_abs_jet_eta: 3.0
  min_abs_jet_eta: 2.5
  min_jet_neef: 0.9
  min_dphi: 3.0 # Minimum dphi between pf-met and jet

HBHENoise:
  min_pfmet: 200.0
  num_jets_ptgt25: 1
  num_jets_ptgt200: 1
  min_jet_pt: 200.0
  max_abs_jet_eta: 3.0
  min_jet_nhef: 0.9
  min_dphi: 3.0 # Minimum dphi between pf-met and jet

Others:
  min_pfmet: 200.0

